name: Update data 
on: [push]

jobs: 
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages dependencies 
        run: 
          Rscript -e "install.packages(c('tidyverse', 'vroom','RCurl'))"
      - name: Run script
        run: 
          Rscript -e "source('script/1_extract_data_covid.R')"
      - name: Commit results 
        run: |  
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git checkout -B deploy
         git add -f public/
         git commit -m "Build front-end assets"
         git push -f origin deploy
