name: Update data 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages dependencies 
        run: 
          Rscript -e "install.packages(c('tidyverse','vroom'))"
      - name: Run script
        run: 
          Rscript -e "source('./1_extract_data_covid.R')"
      - name: Commit results 
        run: |  
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push
