name: test
on:
  schedule: 
    - cron:  '*/15 * * * *'
  push:
      branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
